params:
  task:
    log_name: logs/assembly.log
    workcell_name: MAR_PEG_85
    roadmap_location: "/home/aidanc/multi-robot-assembly/apa_workcells/mar_peg_85.graph" 
    checkpoint_file: "/home/aidanc/multi-robot-assembly/multi_arm_assembly/logs/rl_games/apa_impedance/2024-11-12_23-30-19/nn/apa_impedance.pth" 
    socket_addr: tcp://127.0.0.1:6667

  seed: 42

  # environment wrapper clipping
  env:
    # added to the wrapper
    clip_observations: 5.0
    # can make custom wrapper?
    clip_actions: 1.0

  algo:
    name: my_agent

  model:
    name: my_actor_model

  # doesn't have this fine grained control but made it close
  network:
    name: my_network
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None
    
    rnn:
      name: lstm
      units: 256
      layers: 2
      before_mlp: True
      concat_input: True
      layer_norm: False

  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: '' # path to the checkpoint to load

  config:
    name: apa_impedance
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    num_actors: 1  # configured from the script (based on num_envs)
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau : 0.95
    learning_rate: 3e-4
    lr_schedule: None
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: 10000
    save_best_after: 20
    save_frequency: 25
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 100
    minibatch_size: -1
    mini_epochs: 8
    critic_coef: 1
    clip_value: True
    seq_length: 4
    bounds_loss_coef: 0.0001
        
    player:
      render: False
      games_num: 1
      deterministic: False
